language: erlang

notifications:
  recipients:
    - radoslaw.szymczyszyn@erlang-solutions.com

otp_release:
  - 20.3
  - 21.0

before_install:
  - git clone git://github.com/elixir-lang/elixir --depth 1
  - make -C elixir

before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: "MIX_ENV=test mix do deps.get, test"
